cookies:
  path: "cookies"       # Папка с файлами cookies
  file: "cookies.txt"   # Имя файла cookies по умолчанию
cookies_path: "cookies/cookies.txt"
output_dir: "downloads"        # Папка для сохранения видео

# Upload destination: "yandex" or "peertube"
upload_destination: "peertube"

# Delete original video file after successful upload (true/false)
# Can be overridden with -keep command line flag
delete_after_upload: true

yandex:
  oauth_token: "y0__xCVkp5xGN-9OCDpjabKEypQzSZ371Ma47Cf74I46WGeEqBf"
  upload_path: "/video_down/"  # Папка на Яндекс.Диске

peertube:
  server_url: "https://peertube.site"
  access_token: "c13f19c86aceadd556b31ddd9a1ed23f97e0211f"
  channel_id: 2
  privacy: 1  # 1=Public, 2=Unlisted, 3=Private, 4=Internal
  wait_transcoding: false
  default_description: "Downloaded from YouTube"