cookies:
  path: "cookies"       # Папка с файлами cookies
  file: "cookies.txt"   # Имя файла cookies по умолчанию
cookies_path: "cookies/cookies.txt"
output_dir: "downloads"        # Папка для сохранения видео
yandex:
  oauth_token: "y0__xCVkp5xGN-9OCDpjabKEypQzSZ371Ma47Cf74I46WGeEqBf"
  upload_path: "/video_down/"  # Папка на Яндекс.Диске